const POST_UPDATE_REQUEST = "POST_UPDATE_REQUEST";
const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
const POST_UPDATE_FAILURE = "POST_UPDATE_FAILURE";

export { POST_UPDATE_FAILURE, POST_UPDATE_SUCCESS, POST_UPDATE_REQUEST };
