export const PAYMET_USER_DETAILS = "PAYMET_USER_DETAILS";
export const POST_USER_DETAILS_REQUEST = "POST_USER_DETAILS_REQUEST";
export const POST_USER_DETAILS_SUCCESS = "POST_USER_DETAILS_SUCCESS";
export const POST_USER_DETAILS_FAILURE = "POST_USER_DETAILS_FAILURE";