const FETCH_FUNDRAISER_REQUEST = "FETCH_FUNDRAISER_REQUEST";
const FETCH_FUNDRAISER_SUCCESS = "FETCH_FUNDRAISER_SUCCESS";
const FETCH_FUNDRAISER_FAILURE = "FETCH_FUNDRAISER_FAILURE";

export {
  FETCH_FUNDRAISER_FAILURE,
  FETCH_FUNDRAISER_SUCCESS,
  FETCH_FUNDRAISER_REQUEST,
};
