export const ADD_CAMPAIGN_REQ = "ADD_CAMPAIGN_REQ";
export const ADD_CAMPAIGN_SUCCESS = "ADD_CAMPAIGN_SUCCESS";
export const ADD_CAMPAIGN_FAILURE = "ADD_CAMPAIGN_FAILURE";

export const UPDATE_CAMPAIGN_REQ = "UPDATE_CAMPAIGN_REQ";
export const UPDATE_CAMPAIGN_SUCCESS = "UPDATE_CAMPAIGN_SUCCESS";
export const UPDATE_CAMPAIGN_FAILURE = "UPDATE_CAMPAIGN_FAILURE";
